### ISSUE TITLE
If you're supposed to suggest a bug here, then what is the Bugs repo?

### ISSUE THREAD

**Issue by bjskistad** [LilCoders/Lilcoders#2]

**Comment by bjskistad** [comment]
Just close? No answer?

**Comment by herohamp** [comment]
xD

**Comment by herohamp** [comment]
I cant seem to find the bugs repo oddly...

http://image.prntscr.com/image/1d1af0148dd144edabd36195bae32cb1.png

**Comment by CosmicWebServices** [comment]
THERE WHERE ISSUES WE NEED TO FIX THERE!!!!!!!!!!!!!

**Comment by herohamp** [comment]
whoops sorry xD

**Comment by CosmicWebServices** [comment]
ugh guess we need to remeber what they are

**Comment by bjskistad** [comment]
Lol.
